version: '3'
services:
  ts-zk:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - task-scheduler-network
  ts-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_ZOOKEEPER_CONNECT: ts-zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - task-scheduler-network
networks:
  task-scheduler-network:
    external: true
